name: camera_web_integration_tests
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

dependencies:
  camera_platform_interface: 
    git: https://github.com/kumsumit/camera_platform_interface.git
  camera_web:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.11.0
  cross_file: ^0.3.3+5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: 0.3.0
